function T = T4(alpha,a,d,theta)
%this function uses the parameters of DH table and returns homogenious transformation matrix
    T =simplify([sin(theta+pi/2)              , -sin(theta)                     , 0               , a                  ; ...
                 sin(theta)*sin(alpha + pi/2)  , sin(theta+pi/2)*sin(alpha+pi/2)  , -sin(alpha)    , -sin(alpha)*d     ; ...
                 sin(theta)*sin(alpha)       , sin(theta+pi/2)*sin(alpha)     , sin(alpha+pi/2)  , sin(alpha+pi/2)*d   ; ...
                 0                            , 0                               , 0               , 1]);
end
